// eslint.config.js – version flat config (ESLint v9+ compatible)

import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import importPlugin from 'eslint-plugin-import';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from 'typescript-eslint';

export default [
	js.configs.recommended,
	...tseslint.configs.recommended,
	{
		files: ['**/*.{ts,tsx,js,jsx}'],
		languageOptions: {
			parser: tseslint.parser,
			parserOptions: {
				ecmaVersion: 'latest',
				sourceType: 'module',
				ecmaFeatures: {
					jsx: true,
				},
			},
			globals: {
				browser: true,
				node: true,
				window: true,
				document: true,
				console: true,
			},
		},
		settings: {
			react: {
				version: 'detect',
			},
			'import/resolver': {
				typescript: {
					project: '.',
					extensions: ['.js', '.jsx', '.ts', '.tsx'],
				},
			},
		},
		plugins: {
			react,
			reactHooks,
			'react-refresh': reactRefresh,
			import: importPlugin,
			'jsx-a11y': jsxA11y,
		},
		rules: {
			'react-refresh/only-export-components': 'warn',
			indent: ['warn', 'tab', { SwitchCase: 1 }],
			semi: ['warn', 'always'],
			quotes: ['warn', 'single'],
			'linebreak-style': 'off',
			'array-bracket-spacing': ['warn', 'always'],
			'computed-property-spacing': ['warn', 'always'],
			'comma-dangle': [
				'warn',
				{
					arrays: 'always-multiline',
					objects: 'always-multiline',
					imports: 'always-multiline',
					exports: 'always-multiline',
					functions: 'never',
				},
			],
			'arrow-spacing': 'warn',
			'key-spacing': ['warn', { beforeColon: false, afterColon: true, mode: 'strict' }],
			'no-multi-spaces': 'warn',
			'no-multiple-empty-lines': 'warn',
			'no-empty-function': 'warn',
			'require-await': 'error',
			'template-curly-spacing': ['warn', 'always'],
			'brace-style': ['warn', '1tbs'],
			'prefer-destructuring': [
				'warn',
				{
					VariableDeclarator: { array: true, object: true },
					AssignmentExpression: { array: true, object: true },
				},
				{ enforceForRenamedProperties: false },
			],
			'one-var-declaration-per-line': ['error', 'always'],
			'one-var': ['error', 'never'],
			'rest-spread-spacing': ['warn', 'never'],
			'no-param-reassign': 'error',
			'no-constant-binary-expression': 'error',
			'no-new-native-nonconstructor': 'error',
			'object-curly-spacing': ['warn', 'always'],
			'object-property-newline': 'warn',
			'object-curly-newline': [
				'warn',
				{
					ObjectExpression: { multiline: true, minProperties: 2 },
					ObjectPattern: { multiline: true },
					ImportDeclaration: 'never',
					ExportDeclaration: { multiline: true, minProperties: 3 },
				},
			],
			'prefer-object-has-own': 'warn',
			'prefer-object-spread': 'warn',
			'object-shorthand': 'warn',
			'func-names': ['warn', 'as-needed'],
			'no-func-assign': 'error',
			'default-case': 'warn',
			'default-case-last': 'warn',
			'no-duplicate-case': 'warn',
			'no-constant-condition': 'warn',
			'no-self-compare': 'error',
			'for-direction': 'warn',
			'no-unmodified-loop-condition': 'error',
			'no-var': 'error',
			'no-const-assign': 'error',
			'no-multi-assign': 'warn',
			'no-self-assign': ['warn', { props: true }],
			'no-use-before-define': 'warn',
			'new-cap': ['warn', { capIsNew: false, newIsCap: true }],
			'no-constructor-return': 'error',
			'no-unused-private-class-members': 'warn',
			'no-promise-executor-return': 'error',
			'valid-typeof': 'error',
			'no-template-curly-in-string': 'error',
			'import/no-unresolved': 'error',
			'import/order': [
				'warn',
				{
					groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index', 'unknown'],
					pathGroups: [{ pattern: '{.,..}/*.css', group: 'sibling', position: 'after' }],
					alphabetize: { order: 'asc', caseInsensitive: true },
					'newlines-between': 'always',
				},
			],
			'no-duplicate-imports': ['error'],
			'no-class-assign': 'error',
			'react/react-in-jsx-scope': 'off',
			'react/jsx-uses-react': 'off',
			'react/jsx-filename-extension': ['error', { extensions: ['.jsx', '.tsx'] }],
			'react/jsx-uses-vars': 'warn',
			'react/no-unescaped-entities': 'warn',
			'react/destructuring-assignment': 'warn',
			'react/jsx-one-expression-per-line': 'off',
			'react/function-component-definition': [
				'warn',
				{ namedComponents: 'arrow-function', unamedComponents: 'arrow-function' },
			],
			'react/jsx-closing-bracket-location': ['warn', 'tag-aligned'],
			'react/jsx-closing-tag-location': 'warn',
			'react/jsx-curly-brace-presence': 'warn',
			'react/jsx-curly-newline': ['warn', { multiline: 'consistent', singleline: 'forbid' }],
			'react/jsx-curly-spacing': ['warn', { when: 'always', children: true }],
			'react/button-has-type': 'warn',
			'react/jsx-boolean-value': 'warn',
			'react/hook-use-state': 'warn',
			'react/jsx-fragments': 'warn',
			'react/jsx-handler-names': ['warn', { checkLocalVariables: true, checkInlineFunction: true }],
			'react/jsx-pascal-case': 'warn',
			'react/jsx-no-leaked-render': 'error',
			'react/jsx-no-constructed-context-values': 'error',
			'react/jsx-no-comment-textnodes': 'warn',
			'react/jsx-indent': [
				'warn',
				'tab',
				{ indentLogicalExpressions: true, checkAttributes: true },
			],
			'react/jsx-no-bind': ['warn', { allowArrowFunctions: true }],
			'react/jsx-wrap-multilines': 'warn',
			'react/no-array-index-key': 'error',
			'react/no-danger': 'error',
			'react/no-deprecated': 'error',
			'react/no-multi-comp': 'error',
			'react/no-this-in-sfc': 'error',
			'react/no-typos': 'error',
			'react/no-unstable-nested-components': 'error',
			'react/no-unused-state': 'warn',
			'react/no-children-prop': 'error',
			'react/jsx-props-no-multi-spaces': 'warn',
			'react/jsx-sort-props': [
				'warn',
				{ shorthandLast: true, callbacksLast: true, reservedFirst: ['key'] },
			],
			'react/jsx-indent-props': ['warn', { indentMode: 'tab', ignoreTernaryOperator: true }],
			'react/jsx-no-duplicate-props': 'error',
			'react/prop-types': 'off',
			'react/no-unused-prop-types': 'warn',
			'react/forbid-prop-types': 'warn',
			'react/boolean-prop-naming': ['error', { validateNested: true }],
			'react/jsx-max-props-per-line': ['warn', { maximum: 1 }],
			'react/jsx-first-prop-new-line': ['warn', 'multiline'],
			'react/jsx-props-no-spreading': [
				'warn',
				{
					html: 'enforce',
					custom: 'ignore',
					explicitSpread: 'enforce',
					exceptions: ['button', 'a', 'input'],
				},
			],
			'react/require-default-props': 'off',
			'react/prefer-es6-class': 'error',
			'react/state-in-constructor': ['warn', 'always'],
			'react/no-access-state-in-setstate': 'warn',
			'react/no-arrow-function-lifecycle': 'warn',
			'react/no-did-mount-set-state': 'error',
			'react/no-did-update-set-state': 'error',
			'react/no-invalid-html-attribute': 'error',
			'react/no-redundant-should-component-update': 'error',
			'react/no-unused-class-component-methods': 'warn',
			'jsx-quotes': ['warn', 'prefer-double'],
			'jsx-a11y/no-static-element-interactions': 'error',
			'jsx-a11y/anchor-is-valid': 'off',
			'jsx-a11y/mouse-events-have-key-events': 'off',
			'jsx-a11y/click-events-have-key-events': 'off',
			'jsx-a11y/no-noninteractive-element-interactions': 'off',
			'@typescript-eslint/no-unused-vars': 'warn',
			'@typescript-eslint/object-curly-spacing': ['warn', 'always'],
		},
	},
	prettier,
];
